### ISSUE TITLE
get file mime type error

### ISSUE THREAD

**Issue by kokokobe** [Addicticks/httpsupload#2]
URLConnection.guessContentTypeFromName(file.getAbsolutePath())

**Comment by addicticks-dev** [comment]
Hi Kokokobe

Exactly what do you mean by this ticket? 
Please elaborate. 

Thanks

**Comment by kokokobe** [comment]
source code UploadItem  mime type is null but also added to headers       
 for (UploadItem uItem : uploadFiles) {
            String uploadFormFieldName =  uItem.getFormFieldName();
            String mimeType = uItem.getMimeType();
            String hintFilename = uItem.getHintFilename();
            ArrayList<String> mpHeaders = new ArrayList();
            ArrayList<String> mpFooters = new ArrayList();

            // Multi-part headers
            mpHeaders.add(TWOHYPHENS + MULTIPART_BOUNDARY + CRLF);
            mpHeaders.add("Content-Disposition: form-data; name=\"" + uploadFormFieldName + "\";filename=\"" + hintFilename + "\"" + CRLF);
            mpHeaders.add("Content-Type: " + mimeType + CRLF);
            mpHeaders.add(CRLF);

**Comment by addicticks-dev** [comment]
Thanks.  Got it now.  The JDK's [URLConnection.guessContentTypeFromName()](https://docs.oracle.com/javase/8/docs/api/java/net/URLConnection.html#guessContentTypeFromName-java.lang.String-) actually returns `null` if the the type cannot be guessed from the argument. This is undocumented by Oracle.

In any case, there's no path in the code to explicitly handle this situation so the library will end up setting a HTTP header `Content-type: null`  which is illegal. This is a bug. 

Thanks for reporting.

**Comment by addicticks-dev** [comment]
Fixed in 9dea6db2769eb0e019c79eb8547b85ee8e6c47fb. Now a MIME type of `application/octet-stream` will be used if everything else fails.

The new version 1.2.3 has been pushed to Maven Central. It may take some minutes for it to arrive.
